server:
  port: 8763

spring:
  application:
    name: user-service
  zipkin:
    base-url: http://localhost:9411

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true #向服务注册中心注册自己
    fetch-registry: true #获取服务列表
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream