server:
  port: 8769

eureka:
  server:
    enable-self-preservation: false #关闭自我保护，防止服务踢出不及时
  instance:
    hostname: peer2
  client:
    registerWithEureka: false #不需要注册服务
    fetchRegistry: false #不需要获取服务列表
    serviceUrl:
      defaultZone: http://peer1:8761/eureka/,http://peer1:8769/eureka/

spring:
  profiles: peer2
  application:
    name: eurka-server