eureka:
  client:
    serviceUrl:
      defaultZone: http://peer1:8761/eureka/,http://peer1:8769/eureka/
    fetch-registry: true #获取服务列表
    register-with-eureka: false #不需要注册自己
    registry-fetch-interval-seconds: 1 #从服务端获取服务列表周期，默认30s
server:
  port: 8764
spring:
  application:
    name: service-ribbon
