eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true #获取服务列表
    register-with-eureka: false #不需要注册自己
server:
  port: 8764
spring:
  application:
    name: service-ribbon
